### ISSUE TITLE
python-wrapper not working

### ISSUE THREAD

**Issue by dk-teknologisk-bgd** [hank-ai/darknet#91]
It seems that the python-function "darknet.load_network()" returns an integer instead of a tuple, which causes basically all python files in src-python to fail. Example from running darknet_images.py:

 0 : compute_capability = 750, cudnn_half = 1, GPU: Tesla T4 
Allocating workspace to transfer between CPU and GPU:  50.0 MiB
Traceback (most recent call last):
  File "/home/bgd/GIT/darknet/src-python/darknet_images.py", line 442, in <module>
    main()
    ~~~~^^
  File "/home/bgd/GIT/darknet/src-python/darknet_images.py", line 430, in main
    network, class_names, class_colors = darknet.load_network(

Does anyone have a fix for this? 

print out from darknet version:
Darknet V3 "Jazz" v3.0-194-g3b4dc0e7
CUDA runtime version 12030 (v12.3), driver version 12030 (v12.3)
cuDNN version 12060 (v9.5.1), use of half-size floats is ENABLED
=> 0: Tesla T4 [#7.5], 14.6 GiB
OpenCV v4.2.0, Ubuntu 20.04, kvm

**Comment by stephanecharette** [comment]
The python example is working for me as far as I can tell.

![image](https://github.com/user-attachments/assets/36ad4b5d-0099-4c8d-896b-aafa1542e2d2)

**Comment by dk-teknologisk-bgd** [comment]
Something is off.

If you look at line 430 in darknet_images.py, darknet.load_network() is expected to return three values.

But in darknet.py, in line 113 load_network() only returns a single value.

let me know if im in the wrong.

**Comment by stephanecharette** [comment]
If you're on V3, then use the `example.py` script.  The other scripts are from V2, which I guess haven't been updated yet.
